import Layout from "@/components/Layout/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePicture from "../assets/img/profile.png";
import AnimatedText from "@/components/Animations/AnimatedText/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons/Icons";
import HireMe from "@/components/Animations/HireMe/HireMe";
import lightBulb from "../assets/svg/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/Animations/TransitionEffect/TransitionEffect";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}

export default function Home() {
  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />

      <main className="flex items-center text-dark w-full min-h-screen dark:text-light 2xl">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/4 md:w-1/2">
              <Image
                src={profilePicture}
                alt="Lucas Mitori"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <h1></h1>
              <AnimatedText
                text="Developing projects with innovation and passion"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I&apos;m dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js in
                front-end and Node.js in back-end.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/docs/curriculo_dev_lm.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                   hover:bg-light hover:text-dark border-solid border-transparent hover:border-dark border-2
                    dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                     hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:lucas.mitori@hotmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image
            src={lightBulb}
            alt="LucasMitori"
            className="w-full h-auto md:hidden"
          />
        </div>
      </main>
    </>
  );
}
